package com.enterprisearchitecture.codereview;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class JobDetailArray implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Job Detail List")
	private java.util.List<com.enterprisearchitecture.codereview.Job> jobArray;

	public JobDetailArray() {
	}

	public java.util.List<com.enterprisearchitecture.codereview.Job> getJobArray() {
		return this.jobArray;
	}

	public void setJobArray(
			java.util.List<com.enterprisearchitecture.codereview.Job> jobArray) {
		this.jobArray = jobArray;
	}

	public JobDetailArray(
			java.util.List<com.enterprisearchitecture.codereview.Job> jobArray) {
		this.jobArray = jobArray;
	}

}